### ISSUE TITLE
Usage with babel and uglifyJs

### ISSUE THREAD

**Issue by t47io** [indutny/webpack-common-shake#12]
Hi, may I ask for some more hints on how to use this together with other `webpack` ecosystem things? (Already looked at [`webpack-common-shake-demo`](https://github.com/indutny/webpack-common-shake-demo).

More specifically,
- An example config with `babel-loader`?
- Does it matter for the order of `plugins`? Should `ShakePlugin` go before or after `UglifyJSPlugin`?

Thanks!

**Comment by indutny** [comment]
Hello!

There is only one important thing about using this plugin. It should be used **before** UglifyJSPlugin. Otherwise, other plugins may be used at any time at all.

Hope this helps,
Fedor.
