### ISSUE TITLE
Shakes exports when they're used

### ISSUE THREAD

**Issue by kurtextrem** [indutny/webpack-common-shake#23]
This is the code:
```
var propTypes={
light:_propTypes2.default.bool,
dark:_propTypes2.default.bool,
inverse:(0,_utils.deprecated)(_propTypes2.default.bool,'Please use the prop "dark"')
}
```

However, the "exports" in front of "deprecated" in the original file gets shaken out, so when the code is executed it throws an error.

**Comment by jkrems** [comment]
Thanks for reporting this!

1. Can you check if this still happens with the latest version?
2. If so, can you write up a full failing test case that can be run? It's hard to gauge from the snippet above where the issue might stem from. :)

**Comment by kurtextrem** [comment]
Hi @jkrems. Sorry for the late reply, busy with Uni.

It's working now. Thanks a lot!
