### ISSUE TITLE
Cannot read property 'resource' of null

### ISSUE THREAD

**Issue by dhruvdutt** [indutny/webpack-common-shake#24]
![image](https://user-images.githubusercontent.com/5961873/36430023-2bce5cca-167a-11e8-8d36-41d148ae1fb4.png)

package.json
```
"webpack": "^4.0.0-beta.2",
"webpack-cli": "^2.0.6",
"webpack-common-shake": "^1.5.3",
"webpack-dev-server": "^2.11.1"
```

[.babelrc](https://gist.github.com/dhruvdutt/d66526c8a3d6778328781f88ced6fc54#file-babelrc)

[webpack.config.js](https://gist.github.com/dhruvdutt/d66526c8a3d6778328781f88ced6fc54#file-webpack-config-js)

**Comment by dhruvdutt** [comment]
Related issue #3

**Comment by jdalton** [comment]
I'm seeing this too while I upgrade from Webpack 3 to Webpack 4.

**Comment by jkrems** [comment]
Same when upgrading to webpack 4.

**Comment by jkrems** [comment]
v2.0.0 was just published which should work with webpack 4.
