### ISSUE TITLE
Cannot read property 'resource' of undefined

### ISSUE THREAD

**Issue by aewing** [indutny/webpack-common-shake#3]
I've recently attempted to implement this package into my build chain using Webpack 3.
Unfortunately, with this plugin added, my build fails at around 80%, citing the following error:

```
TypeError: Cannot read property 'resource' of undefined
    at ShakePlugin.mapModule (/path/to/node_modules/webpack-common-shake/lib/shake/plugin.js:71:33)
```

This is on MacOS with Node v6.11.0

**Comment by indutny** [comment]
Should be fixed now, I hope. Thanks!
