### ISSUE TITLE
webpack4 build error?

### ISSUE THREAD

**Issue by myzhibie** [indutny/webpack-common-shake#30]
![image](https://user-images.githubusercontent.com/8846963/45029305-d3c1eb00-b07a-11e8-8e44-73965dd814ce.png)
This plugin does not support webpack 4.16.4?

**Comment by jkrems** [comment]
This looks like the same issue I ran into: https://github.com/indutny/webpack-common-shake/pull/29

The short version is that this seems to be triggered by a very specific combination of imports. There's a minimal (?) reproduction in the PR above but I haven't had time yet to investigate it any deeper.
